chapter1_02_statistical-models.md (#2)
hiroshi-matsuda-rit/spacy-course pull request #13
Opened 2020-09-12 14:53 UTC by icoxfog417

Chapter1の日本語訳 (#2)

## chapter1_02_statistical-models.md

翻訳時期になった点。

* UD_Japanese-GSDのコーパスの出自がわからない。`Web文章で訓練された`でいいのか?(名前的にニュースなのかもだが・・・)
* 依存関係ラベルの名称: [Universal Dependency日本語コーパス](https://www.jstage.jst.go.jp/article/jnlp/26/1/26_3/_pdf)
* パッケージ画像(`package_ja.png`)の差し替えを行う際の、モデル名のフォント(spaCyチュートリアルのfont-familyを参照し、かつ手元のソフトに入っているフォント(Arial)を採用)。

2020-09-12 15:30 UTC, tamuhey approved these changes

2020-09-12 15:33 UTC, tamuhey commented
@icoxfog417 ありがとうございます！

> 依存関係ラベルの名称
> Universal Dependency日本語コーパス を参照して付与。

はい、こちらの名称よいです

> パッケージ画像(package_ja.png)の差し替えを行う際の、モデル名のフォント
> spaCyチュートリアルのfont-familyを参照し、かつ手元のソフトに入っているフォント(Arial)を採用。ちょっと違う感じだが、そんなにこだわるところでもないか??

これでOKだと思います！（後々authorの @ines に確認します)

@hiroshi-matsuda-rit 以下お答えいただけると！

> UD_Japanese-GSDのコーパスの出自がわからない

2020-09-13 11:14 UTC, hiroshi-matsuda-rit commented
> UD_Japanese-GSDのコーパスの出自がわからない
> Web文章で訓練されたでいいのか?(名前的にニュースなのかもだが・・・)。
はい。Webテキストが出自ということで間違いありません。内容的に報道的なものが多いためspaCy側がnewsと判断した可能性がありますが、出発物としての新聞記事は含まれていないはずです。

これから解析内容の確認に入りますね。

2020-09-13 11:57 UTC, hiroshi-matsuda-rit requested changes
例文のトヨタをアップルに変更したいと思います。ソース上のコメントを確認ください。

2020-09-13 11:57 UTC, hiroshi-matsuda-rit commented on chapters/ja/slides/chapter1_02_statistical-models.md
> +doc = nlp("トヨタはイギリスのスタートアップを10億円で買いそうだ")
原文のまま、アップルとしませんか？
解析結果もアップルがORGと認識されます。
調べたところトヨタによる10億円の買収案件は確認できなかったため、関係者からクレームが入る可能性を考慮しての意見です。

2020-09-14 00:22 UTC, icoxfog417 commented on chapters/ja/slides/chapter1_02_statistical-models.md
> +doc = nlp("トヨタはイギリスのスタートアップを10億円で買いそうだ")
翻訳するなら日本企業にしようかな、という意図のみなのでOKです。

2020-09-14 02:09 UTC, merged

2020-09-14 02:09 UTC, hiroshi-matsuda-rit commented
@icoxfog417 ご対応いただき大変ありがとうございました！引き続きどうか宜しくお願いいます。