Translate slides in chapter 4 (#5)
hiroshi-matsuda-rit/spacy-course pull request #15
Opened 2020-09-13 05:13 UTC by HiromuHota

This will fix #5.

### A. 以下のファイルの英語例文を日本語に翻訳する
* [x]  chapters/ja/slides/chapter4_01_training-updating-models.md
* [x]  chapters/ja/slides/chapter4_02_training-loop.md
* [x]  chapters/ja/slides/chapter4_03_training-best-practices.md
* [x]  chapters/ja/slides/chapter4_04_wrapping-up.md

### B. 以下のファイルで英語モデルを指定しているコード中の記述とその出力例を日本語モデルのものに置き換える
* [ ]  chapters/ja/slides/chapter4_01_training-updating-models.md
* [ ]  chapters/ja/slides/chapter4_02_training-loop.md
* [ ]  chapters/ja/slides/chapter4_03_training-best-practices.md
* [ ]  chapters/ja/slides/chapter4_04_wrapping-up.md

### C. 以下のファイルに対する変更が日本語モデルの解説として適切なものとなるよう見直しを行う
* [ ]  chapters/ja/slides/chapter4_01_training-updating-models.md
* [ ]  chapters/ja/slides/chapter4_02_training-loop.md
* [ ]  chapters/ja/slides/chapter4_03_training-best-practices.md
* [ ]  chapters/ja/slides/chapter4_04_wrapping-up.md

2020-09-13 05:51 UTC, HiromuHota commented
@hiroshi-matsuda-rit 
045e2f7で既に作業Bも完了していると思いましたが、認識に相違ありませんか？

2020-09-13 05:59 UTC, HiromuHota commented on chapters/ja/slides/chapter4_02_training-loop.md
> +Notes: この例ではまず `spacy.blank` メソッドを使用して空の日本語モデルを作成します。空のモデルにはパイプラインコンポーネントはなく、言語データとトークン化ルールだけ入っています。
> 空のモデルにはパイプラインコンポーネントはなく、言語データとトークン化ルールだけ入っています。

作業Cの観点で、この記述は少し誤っているとの認識です。
日本語モデルは例外で、トークナイザーがタグ付けも行っている、と理解しています。

2020-09-13 06:29 UTC, tamuhey requested changes

2020-09-13 06:29 UTC, tamuhey commented on chapters/ja/slides/chapter4_02_training-loop.md
> +Notes: この例ではまず `spacy.blank` メソッドを使用して空の日本語モデルを作成します。空のモデルにはパイプラインコンポーネントはなく、言語データとトークン化ルールだけ入っています。
そうですね。以下のように変更するのが良いと思うのですが、いかがでしょう？

```
空のモデルにはパイプラインコンポーネントはなく、分かち書きとタグ付を行うトークナイザと言語データだけが入っています。
```

2020-09-13 06:41 UTC, tamuhey commented
ありがとうございます！リクエストを出した部分を修正して頂ければ、Cまで完了で良いかと思います！

2020-09-13 13:10 UTC, hiroshi-matsuda-rit commented
更新範囲についてコードをレビューし、問題ないことを確認しました。ありがとうございます。 @HiromuHota 

chapters/ja/slides/chapter4_02_training-loop.md の後半の例に出てくる examples に何を設定するかについて明示はされていませんが、もともとこういう例なのでこのままで良いでしょうか。 @tamuhey

2020-09-13 21:43 UTC, HiromuHota commented on chapters/ja/slides/chapter4_02_training-loop.md
> +Notes: この例ではまず `spacy.blank` メソッドを使用して空の日本語モデルを作成します。空のモデルにはパイプラインコンポーネントはなく、言語データとトークン化ルールだけ入っています。
@tamuhey ご提案ありがとうございます。
- 日本語モデル以外では、空のモデルには言語データとトークン化ルールだけしか入っていない
- 日本語のコースを受講したとしても、他の言語モデル（特に英語）を使用することが想定される

以上のことから、ご提案の文章では少し誤解を招く（英語モデルでもタグ付を行ってくれると誤解される）可能性があるかと思い、例外として記載することにしました。いかがでしょうか？

2020-09-14 01:39 UTC, tamuhey commented on chapters/ja/slides/chapter4_02_training-loop.md
> +Notes: この例ではまず `spacy.blank` メソッドを使用して空の日本語モデルを作成します。空のモデルにはパイプラインコンポーネントはなく、言語データとトークン化ルールだけ入っています。
たしかにそうですね、そのように例外として記載してください。ありがとうございます！

2020-09-14 01:40 UTC, tamuhey approved these changes

2020-09-14 01:43 UTC, tamuhey commented
> chapters/ja/slides/chapter4_02_training-loop.md の後半の例に出てくる examples に何を設定するかについて明示はされていませんが、もともとこういう例なのでこのままで良いでしょうか。

@hiroshi-matsuda-rit はい、これでいいと思います！

@HiromuHota ありがとうございました！

2020-09-14 01:43 UTC, merged