Translate slide contents in Chapter 2: Work A
hiroshi-matsuda-rit/spacy-course pull request #17
Opened 2020-09-18 04:00 UTC by forest1988

#3 について、作業A を完了したつもりでおります。ご確認をお願いいたします。

## slides/chapter2_02_data-structures-2.md

- Hello World! → こんにちは世界！
    - エクスクラメーションマークも半角から全角にしました。

## slides/chapter2_03_word-vectors-similarity.md

> Notes: spaCyを使うと、2つのオブジェクトを比較し、類似度を予測できます。例えば、doc、span、tokenなどです。

については、冒頭の

> Notes: このレッスンではspaCyを使って、文章やスパン、トークン間の類似度を予測する方法を学んでいきます。

と合わせ、 doc、span、token を文章、スパン、トークンと訳しても良いかと思いましたが、ひとまずママで残しました。

## slides/chapter2_04_models-rules.md

ここでは、「have (a dog)」を「飼っている」と訳出しました。

また、現状では動作を確認しておりませんので、以下の、出力確認が必要な部分については訳出しておりません。

>最後に、前のトークンとその属性をみていきます。この場合は限定詞「a」です。

> これによって、マッチした「Golden Retriever」の`Span`オブジェクトを作ることができ、文脈を解析できます。

以上、どうぞよろしくお願いいたします。

2020-09-18 17:47 UTC, forest1988 commented
失礼しました、プルリクの仕様をよく理解しておりませんでした。
一度プルリクを出すと、プルリク元のブランチに push した場合に、それもプルリクに反映されてしまうのですね。

work B に関する commit も追加されてしまったので、 pull request の名称を再検討します。

2020-09-19 04:13 UTC, forest1988 commented
#3 について、Chapter2_04 まで作業B が完了したと思われますので、これもこのプルリクに含め、タイトルから [WIP] を外させていただきました。
よろしくお願いいたします。

2020-09-20 08:09 UTC, hiroshi-matsuda-rit approved these changes
@tamuhey コードレビュー完了です。

2020-09-20 15:08 UTC, tamuhey commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
@hiroshi-matsuda-rit @forest1988 こちら、ラベルはそのまま英語にしておいてください！

2020-09-20 18:48 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
@hiroshi-matsuda-rit コードレビューをいただきありがとうございます。Spanのラベルについて、以降の事例と共通性を持たせるために英語のままとするのはどうかとのこと、承知しました。

2020-09-20 18:54 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
この修正につきまして、私のほうで作業を行い、 forest1988:fix/3 ブランチを更新すれば宜しいでしょうか？　それとも、別の手順となりますでしょうか？　
不慣れで恐縮ですが、ご教示いただけますと幸いです。

2020-09-20 18:57 UTC, hiroshi-matsuda-rit commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
遅くまでありがとうございます😌
現在のブランチで遠慮なく更新かけていって下さい。
ブランチの更新は自動的にこのプルリクに反映されていきます。

2020-09-21 02:05 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
労いの言葉を頂戴しありがとうございます！
現在のブランチで更新をかけていって良いとのこと、承知しました。
ブランチの更新が自動的にプルリクに反映されるとのこと、お教えいただきありがとうございます。

いただいたコードレビューを反映する更新をかけさせていただきました。プルリクにも反映されているようですので、ご確認をいただけますでしょうか？

2020-09-21 03:40 UTC, hiroshi-matsuda-rit commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
はい、こちらで問題ありません！

2020-09-21 03:42 UTC, hiroshi-matsuda-rit approved these changes
@tamuhey 翻訳面で問題ないようでしたらマージをお願いします。

2020-09-21 05:23 UTC, tamuhey requested changes

2020-09-21 06:08 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
承知しました、ご確認ありがとうございます。

2020-09-21 06:09 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +  - **トークン属性を使える場合は、それを使いましょう。**　例えば、`token.i`をトークンのインデックスとして使いましょう
承知しました、すぐに修正いたします。

2020-09-21 06:13 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +  - **トークン属性を使える場合は、それを使いましょう。**　例えば、`token.i`をトークンのインデックスとして使いましょう
修正いたしました。ご確認をお願いいたします。

2020-09-21 06:16 UTC, forest1988 commented on chapters/ja/slides/chapter2_02_data-structures-2.md
> +span_with_label = Span(doc, 0, 2, label="挨拶")
ありがとうございます！

2020-09-21 11:07 UTC, tamuhey approved these changes
ありがとうございます！

2020-09-21 11:08 UTC, merged