[WIP] Translate non-slide contents, exercises, and data in Chapter 4 (#7)
hiroshi-matsuda-rit/spacy-course pull request #18
Opened 2020-09-19 02:53 UTC by akirakubo

`exercises/ja/country_text.txt`は(#7)において列挙されていませんでしたが、`exercises/ja/exc_02_15.py`で読み込まれていて、かつ他の章では使われていないので、英訳対象に含めました。

2020-09-20 08:56 UTC, hiroshi-matsuda-rit approved these changes
@akirakubo 長文を含めた翻訳作業、大変お疲れさまでした。一部細かな部分を追記しましたが、基本的に全て問題ないと思います。有難うございました。
@tamuhey コードレビューOKです。

2020-09-21 06:14 UTC, tamuhey requested changes

2020-09-21 06:14 UTC, tamuhey commented on exercises/ja/country_text.txt
> +冷戦後、国連は平和維持任務を飛躍的に拡大し、10年間で過去40年間を上回る数のミッションを担当した。1988年から2000年までの間に、安 全保障理事会決議の採択件数は2倍以上に増え、平和維持予算は10倍以上に増加した。国連はサルバドール内戦の終結を交渉し、ナミビアで平和維持ミッションを成功させ、アパルトヘイト後の南アフリカとクメール・ルージュ後のカンボジアで民主的な選挙を監督した。1991年、
`安 全保障理事会` スペース削除

2020-09-21 06:46 UTC, akirakubo commented on exercises/ja/exc_02_02_01.py
> +doc = nlp("ネコを飼っています")
224ea44 で修正しました。

2020-09-21 06:47 UTC, akirakubo commented on exercises/ja/test_02_09.py
>      assert "doc[1].vector" in __solution__, "正しいベクトルを取得しましたか？"
83f2b57 で修正しました。

2020-09-21 06:47 UTC, akirakubo commented on exercises/ja/exc_02_10_02.py
> +nlp = spacy.load("jp_core_news_md")
df25f42 で修正しました。

2020-09-21 06:48 UTC, akirakubo commented on exercises/ja/country_text.txt
> +冷戦後、国連は平和維持任務を飛躍的に拡大し、10年間で過去40年間を上回る数のミッションを担当した。1988年から2000年までの間に、安 全保障理事会決議の採択件数は2倍以上に増え、平和維持予算は10倍以上に増加した。国連はサルバドール内戦の終結を交渉し、ナミビアで平和維持ミッションを成功させ、アパルトヘイト後の南アフリカとクメール・ルージュ後のカンボジアで民主的な選挙を監督した。1991年、
6a1ea45 で修正しました。

2020-09-21 06:53 UTC, akirakubo commented
@tamuhey レビュー有難うございます。ご指摘いただいた点を修正しました。
見直し中に、`exercises/ja/solution_02_07.py`のコメントにおいて、品詞名が修正漏れになっていることに気付いたので、追加で修正いたしました。よろしくお願いいたします。

2020-09-21 09:52 UTC, tamuhey approved these changes

2020-09-21 09:52 UTC, tamuhey commented
@akirakubo ありがとうございました！！

2020-09-21 09:52 UTC, merged