Translate non-slide contents, exercises, and data in Chapter 3 (#8)
hiroshi-matsuda-rit/spacy-course pull request #19
Opened 2020-09-19 07:56 UTC by mei28

#8 について作業A, Bを行いました．以下気になったことを書いていきます．

- #7 でcountries.jsonの作業をしてもらっていますが，自分が行なったcapitals.jsonのキーとcountries.jsonを一致させる必要があると思います．
- tweets.jsonに関して，twitter内の機能を利用している語句に関しては翻訳していません．
- countries.jsonがないため，chapter3-12の動作確認はできていません．

確認よろしくお願いします．

2020-09-20 09:36 UTC, hiroshi-matsuda-rit reviewed
@tamuhey 何点かインラインでコメントしましたので対応をお願いします。

2020-09-20 09:36 UTC, hiroshi-matsuda-rit commented on exercises/ja/exc_03_10_02.py
> +doc = nlp("おはようございます、 これは文章です。")
@tamuhey Hello world の訳はいつも悩ましいですが、全体で統一する必要はあるでしょうか。

2020-09-20 09:36 UTC, hiroshi-matsuda-rit commented on exercises/ja/solution_03_10_02.py
> +doc = nlp("おはようございます、 これは文章です。")
excと同様

2020-09-21 06:20 UTC, tamuhey commented on exercises/ja/exc_03_10_02.py
> +doc = nlp("おはようございます、 これは文章です。")
@hiroshi-matsuda-rit 確かに悩ましいですが、そこまで統一することに拘る必要はないかと思うので、各作業者におまかせするのが良いかと思います。いかがでしょう？

2020-09-21 06:21 UTC, tamuhey commented
@mei28 ありがとうございます！
countries.jsonの部分については、#7マージ後にこちらで巻き取ります

2020-09-21 08:55 UTC, hiroshi-matsuda-rit commented on exercises/ja/exc_03_10_02.py
> +doc = nlp("おはようございます、 これは文章です。")
私も統一しない形で良いと思います。

2020-09-21 10:02 UTC, tamuhey commented
test passed

2020-09-21 10:52 UTC, tamuhey requested changes
以下の行について、日本語モデルへの修正をお願いいたします。（diff外のためラインコメントできず、リンクで失礼します）
https://github.com/hiroshi-matsuda-rit/spacy-course/pull/19/files#diff-d175132abc3d823824b25d05429dea0dR59

2020-09-21 10:54 UTC, tamuhey requested changes

2020-09-21 10:54 UTC, tamuhey commented on chapters/ja/chapter3.md
>  <choice>
59行目以下、日本語モデルへの置き換えをお願いいたします。

2020-09-21 11:40 UTC, mei28 commented on chapters/ja/chapter3.md
>  <choice>
わかりました，対応します．

2020-09-21 12:03 UTC, mei28 commented on chapters/ja/chapter3.md
>  <choice>
@tamuhey 
コミット:1771b4d　で置き換えを行いました．

またファストフードとファーストフードの表記揺れも直しました．

2020-09-21 14:44 UTC, tamuhey approved these changes
ありがとうございます！

2020-09-21 14:45 UTC, tamuhey commented
@hiroshi-matsuda-rit approve後mergeお願いいたします！

2020-09-21 18:51 UTC, hiroshi-matsuda-rit approved these changes
ご対応いただきありがとうございました！

2020-09-21 18:52 UTC, merged