Translate non-slide contents, exercises, and data in Chapter 1
hiroshi-matsuda-rit/spacy-course pull request #20
Opened 2020-09-20 06:24 UTC by ao9mame

#6 について作業A, Bが完了しました。

- exc_01_09/solution_01_09.pyについては原文同等の適切な事例（固有表現として『iPhone X』を取得したいが、『Upcoming iPhone X』と余分な名詞まで取得する）が思い浮かばなかったため、検出できなかった固有名詞をスパンで取得するように変更しております。

ご確認の程、よろしくお願いいたします。

2020-09-20 10:33 UTC, hiroshi-matsuda-rit reviewed
@ao9mame 作業いただき誠にありがとうございます。以下、何点かご検討をお願いします。

- 複合名詞のスパン抽出例題

`I like tree kangaroos and narwhals.` の例文は `tree kangaroos` のように2つのトークンで構成される単語を取り出すことが目的だと思いますので、
`私はツリーカンガルーとイルカが好きです。`
や
`私はシベリアンハスキーとイルカが好きです。`
のような例文が適切かと思いますが、いかがでしょうか。

- `Upcoming iPhone X`に対応する例

こちらの「三保の松原」など、ひとまとまりで取れない例としていかがでしょうか。
list(nlp("静岡県にある三保の松原は世界遺産の一部です。").ents)
[静岡県, 三保, 松原]

- LEMMAの例

インラインで書きましたのでご確認いただけますでしょうか。

2020-09-20 10:33 UTC, hiroshi-matsuda-rit commented on chapters/ja/chapter1.md
>    例えば、`{"LEMMA": "be"}`は「is」「was」「being」等にマッチします。
@ao9mame LEMMAの日本語の例は「ある」でいかがでしょうか。
あり(ます)
あっ(た)
あれ(ば)

2020-09-20 10:33 UTC, hiroshi-matsuda-rit commented on exercises/ja/exc_01_12_02.py
> +pattern = [{"POS": ____}, {"LEMMA": ____}]
@tamuhey  パターンの構成の変更可否について判断をお願いできますか？

2020-09-20 10:33 UTC, hiroshi-matsuda-rit commented on exercises/ja/exc_01_12_03.py
> +    "私には年の離れた小さい弟がいます。彼は、甘い卵焼きが好きです"
@tamuhey こちらも事例の変更について確認願います。

2020-09-20 11:37 UTC, ao9mame commented on exercises/ja/exc_01_12_03.py
> +    "私には年の離れた小さい弟がいます。彼は、甘い卵焼きが好きです"
@hiroshi-matsuda-rit 
お忙しい中レビューいただき、ありがとうございます。

ご指摘の内容につきまして、対応が完了いたしました。
ご確認の程、お願いいたします。

※ chapter1.md の表記変更につきましては、exc_01_12_02.pyの例文と
平仄が合わなくなるため @tamuheyさんの確認後に
必要でしたら再度、修正させていただきます。

2020-09-20 11:39 UTC, ao9mame commented
@hiroshi-matsuda-rit 
お忙しい中レビューいただき、ありがとうございます。

ご指摘の内容につきまして、対応が完了いたしました。
ご確認の程、お願いいたします。

※ chapter1.md の表記変更につきましては、exc_01_12_02.pyの例文と
平仄が合わなくなるため @tamuheyさんの確認後に
必要でしたら再度、修正させていただきます。

2020-09-21 11:15 UTC, tamuhey requested changes
@ao9mame ありがとうございます！
テストが通るように、exercises/ja/test_01*.pyの修正をお願いいたします。
テストのやりかたは、[こちら](https://github.com/ines/spacy-course#running-automated-tests)を参照してください。

2020-09-21 11:19 UTC, tamuhey requested changes

2020-09-21 11:19 UTC, tamuhey commented on exercises/ja/exc_01_09.py
> +# 松島のスパンを取得
三保の松原

2020-09-21 11:22 UTC, tamuhey commented on exercises/ja/exc_01_12_02.py
> +pattern = [{"POS": ____}, {"LEMMA": ____}]
@hiroshi-matsuda-rit 良いと思います！

2020-09-21 11:24 UTC, tamuhey commented on exercises/ja/exc_01_12_03.py
> +    "私には年の離れた小さい弟がいます。彼は、甘い卵焼きが好きです"
@hiroshi-matsuda-rit 良いと思います！

2020-09-21 15:00 UTC, ao9mame commented
@tamuhey さん （@hiroshi-matsuda-rit ）
レビューいただき、ありがとうございます。

下記、ご指摘の修正が完了いたしました。
- 松島のスパンを取得 → 三保の松原のスパンを取得
- test_01*.py の修正

ご確認の程、よろしくお願いいたします。

2020-09-21 15:47 UTC, tamuhey approved these changes
@ao9mame ありがとうございます!
@hiroshi-matsuda-rit approve後mergeお願いいたします！

2020-09-21 19:25 UTC, hiroshi-matsuda-rit approved these changes
ご対応いただきありがとうございました！

2020-09-21 19:25 UTC, merged