translate slides of chapter 3
hiroshi-matsuda-rit/spacy-course pull request #23
Opened 2020-10-01 05:15 UTC by matsurih

遅くなりすみません。 #4 に対するPRになります。

## 修正内容
- 日本語訳の修正
  - https://github.com/hiroshi-matsuda-rit/spacy-course/issues/4#issuecomment-691591001 にある内容を含みます
- 英語例文の日本語化
- v2.3におけるja_core_news_smモデルがtaggerを含まない問題に関する注釈
- サンプルコード中の例文の日本語化
  - 必要に応じてコードを微修正しています
  - 出力については基本的にspacy==2.3.2およびja_core_web_smモデルを利用した結果に書き換えています
## 注意点
- パイプラインの図は英語版のままとなっていますのでご注意ください
- チャプターの書き出しや終わりは他のチャプターと統一されていないため、適宜ご調整ください

私用のためあまり時間が取れず抜け漏れがあったりslack上での議論をすべて追いきれていないかもしれませんが、適宜ご指摘ください

2020-10-03 10:58 UTC, tamuhey requested changes

2020-10-03 10:58 UTC, tamuhey commented on chapters/ja/slides/chapter3_03_extension-attributes.md
> +トークン「青」の`._.is_color`プロパティは`True`を返すようになりました。
「青」 -> 「青い」

2020-10-03 10:58 UTC, tamuhey commented
テスト動作確認済み

2020-10-03 11:00 UTC, tamuhey approved these changes
@matsurih 一点こちらで修正しました。ありがとうございます！
@hiroshi-matsuda-rit  approve後mergeお願いいたします！

2020-10-03 11:56 UTC, tamuhey approved these changes

2020-10-03 14:28 UTC, hiroshi-matsuda-rit requested changes
一点だけ修正をお願いします。それ以外は全てOKです！

2020-10-03 14:28 UTC, hiroshi-matsuda-rit commented on chapters/ja/slides/chapter3_02_custom-pipeline-components.md
> +Pipeline: ['custom_component', 'tagger', parser', 'ner']
なぜかクオートが消えていますね。たまたま操作ミスが保存されてしまった感じでしょうか？

2020-10-04 03:16 UTC, tamuhey commented on chapters/ja/slides/chapter3_02_custom-pipeline-components.md
> +Pipeline: ['custom_component', 'tagger', parser', 'ner']
こちら僕の方で修正しました！

2020-10-04 03:17 UTC, merged

2020-10-04 03:18 UTC, tamuhey commented
@matsurih @hiroshi-matsuda-rit ありがとうございます！

2020-10-04 03:20 UTC, matsurih commented
諸々ありがとうございます！